---
title: OVERVIEW - SAP S/4HANA Core Entities
config:
  theme: neutral
  layout: elk
---
erDiagram
    direction lr

    BudgetType ||--o{ Budget : "type"
    Budget ||--o{ BudgetProject : "phanBo"
    Project ||--o{ BudgetProject : "duAn"
    BudgetProject o{--|| GlAccount : "khoanMuc"

    Plant ||--o{ StorageLocation : storageLocations
    Plant ||--o{ WorkCenter : workCenters

    Company }|--|| ControllingArea : controllingArea
    Company ||--o{ Plant : plants
    Company ||--o{ SalesOrganization : salesOrganizations
    Company ||--o{ PurchasingOrganization : purchasingOrganizations
    Company ||--|{ SalesOrder : salesOrders
    Company ||--o{ HouseBank : houseBanks

    GlAccount ||--|| Company : companyCode
    
    CostCenter }|--|| Company : companyCode
    CostCenter }|--|| ProfitCenter : profitCenter
    CostCenter }|--|| Segment : segment
    CostCenter }|--|| ControllingArea : controllingArea
    CostCenter }|--|| Plant : plant
    CostCenter ||--o{ Skf : skfs
    CostCenter ||--o{ GlAccount : glAccounts
    CostCenter ||--|{ WorkCenter : workCenters
    CostCenter ||--|{ ActivityType : activityTypes
    
    InternalOrder ||--|| CostCenter : costCenter
    
    
    ProfitCenter }|--|| Company : companyCode
    ProfitCenter }|--|| Segment : segment
    ProfitCenter }|--|| ControllingArea : controllingArea
    ProfitCenter }|--|| Plant : plant

    SalesOrganization ||--o{ SalesOffice : salesOffices
    SalesOrganization ||--o{ DistributionChannel : distributionChannels
    SalesOrganization ||--o{ Division : divisions
    SalesOrganization ||--o{ SalesArea : salesAreas

    DistributionChannel ||--o{ SalesArea : salesAreas
    Division ||--o{ SalesArea : salesAreas

    PurchasingOrganization ||--o{ PurchasingGroup : purchasingGroups
    PurchasingOrganization ||--o{ Plant : responsiblePlants

    BusinessPartner ||--o| Customer : customer
    BusinessPartner ||--o| Supplier : supplier

    Customer }o--|| SalesOrganization : salesOrganization
    Customer }o--|| DistributionChannel : distributionChannel
    Customer }o--|| Division : division
    Customer }o--|| PaymentTerm : paymentTerm
    Customer }o--|| PaymentMethod : paymentMethod
    Customer }o--|| TaxCode : tax
    Customer }o--|| PlanningGroup : planningGroup
    Customer }o--|| PlanningLevel : planningLevel
    Customer }o--|| CustomerGroup : customerGroup

    Supplier }o--|| PurchasingOrganization : purchasingOrganization
    Supplier }o--|| PaymentTerm : paymentTerm
    Supplier }o--|| PaymentMethod : paymentMethod
    Supplier }o--|| TaxCode : tax

    PurchasingInfoRecord }o--|| Material : material
    PurchasingInfoRecord }o--|| Supplier : supplier
    PurchasingInfoRecord }o--|| PurchasingOrganization : purchasingOrganization

    Material }o--|| MaterialType : materialType
    Material }o--|| MaterialGroup : materialGroup
    Material }o--|| StorageLocation : storageLocation
    Material }o--|| PurchasingOrganization : purchasingOrganization
    Material }o--|| Routing : routing
    Material ||--|{ ProductionOrderComponent : productionOrders
    Material ||--o{ BOM : bomComponents
    Material ||--|{ MaterialSalesData : salesData
    Material }o--|| WBS : wbsElement
    MaterialSalesData }|--|| SalesArea : salesArea

    Material }|--|| Unit: unit
    %% Material


    Routing ||--o{ WorkCenter : workCenters

    WBS ||--|{ SettlementRule : receivedSettlementRules
    %% Production Order
    SalesArea ||--|{ SalesOrder : salesOrders
    Customer ||--|{ SalesOrder : salesOrders
    %% Sale
    GlAccount ||--|{ GlAccountTaxCode : tax
    GlAccountTaxCode }|--|| TaxCode: account

    ChartOfAccounts ||--o{ GlAccount : glAccounts
    GlAccount ||--o{ CostElement : costElements

    WorkCenter ||--|{ ActivityType : activityTypes


    InternalOrder ||--|| WBS : wbsElement

    Project ||--o{ WBS : wbsElements

    ControllingArea }|--|| OperatingConcern : operatingConcern

    HouseBank ||--o{ BankAccount : bankAccounts
    BankAccount ||--|| BankKey : bankKey

    GlAccount ||--|| DocumentType : documentType
    DocumentType ||--o{ ChartOfAccounts : chartOfAccounts


    PR }|--|| Employee: requestedEmployee
    PR }|--|| Employee: approvedEmployee

    PO }|--|| Employee: requestedEmployee
    PO }|--|| Employee: approvedEmployee
    PO ||--o{ POChiTiet : "chiTiet"

    PR }|--|| Department: requestedDepartment
    PR ||--o{ PRChiTiet : "chiTiet"

    PRChiTiet }o--|| Material : "Material"
    PRChiTiet ||--|| WBS : "wbsElement"
    POChiTiet }o--|| "Supplier" : "ncc"
    POChiTiet }o--|| _NganSach : "nganSach"
    POChiTiet }o--|| PR : "pr"
    POChiTiet ||--|| WBS : "wbsElement"

    StorageLocation ||--o{ TonKho : "ton"
    StorageLocation ||--o{ LenhNhapKho : "nhap"
    StorageLocation ||--o{ LenhXuatKho : "xuat"

    TonKho o{--|| Material : "vatTu"

    LenhNhapKho o{--|| PO : "po"
    LenhNhapKho ||--o{ PhieuNhapKho : "phieu"
    LenhXuatKho ||--o{ PhieuXuatKho : "phieu"
    LenhNhapKho ||--|{ LenhNhapKhoChiTiet : "chiTiet"
    PhieuNhapKho ||--|{ PhieuNhapKhoChiTiet : "chiTiet"
    LenhXuatKho ||--|{ LenhXuatKhoChiTiet : "chiTiet"
    PhieuXuatKho ||--|{ PhieuXuatKhoChiTiet : "chiTiet"
    LenhNhapKhoChiTiet o{--|| Material : "vatTu"
    PhieuNhapKhoChiTiet o{--|| Material : "vatTu"
    LenhXuatKhoChiTiet o{--|| Material : "vatTu"
    PhieuXuatKhoChiTiet o{--|| Material : "vatTu"

 %% -------------------------------
    %% 1. Project & Zone Domain
    %% -------------------------------
    Project }|--|| Customer        : "customer_id"
    Zone }o--|| ZoneCategory      : "categories_type_code"
    Zone }o--|| Company           : "company_id"
    Zone }o--|| Project           : "project_id"
    %%  Phase to Zone connection in another section

    %% -------------------------------
    %% 2. Resources & Tasks Domain
    %% -------------------------------
    Resource |o--o| Employee       : "employee_id"
    Resource |o--o| Role           : "primary_role"
    Resource |o--o| Resource       : "parent_resource_id"
    %% Labor, Material, Equipment
    Resource |o--o| ResourceType       : "resource_type"
    Resource ||--o{ User   : "time_approve_manager"
    Resource ||--o{ UMeasure   : "unit_of_measure"
    Resource ||--o{ Currency   : "currency_code"

    Resource ||--o{ Plant : "factory_id"
    Resource ||--o{ Workshop : "workshop_id"
    Resource ||--o{ Workshop : "sub_division_id"
    Resource ||--o{ Shift : "shift_code"

    Task }|--|| Project            : "project_id"
    Task }|--|| WBS                : "wbs_id"
    Task }|--|| Workshop           : "workshop_id"
    Task }|--|| Resource           : "primary_resource_id"

    ResourceTask }|--|| Task        : "task_id"
    ResourceTask }|--|| Resource    : "resource_id"
    ResourceTask }|--|| ResourceType    : "resource_type"

    RoleResource }|--|| Resource    : "resource_id"
    RoleResource }|--|| Role        : "role_id"

    %% -------------------------------
    %% 4. Manufacturing / Plant Domain (BOM, Routing, Workshop)
    %% -------------------------------
    BOM_Detail }|--|| BOM          : ""
    BOM_Detail }|--|| Material     : "component"
    BOM }|--|| Material     : "material_sap"
    BOM }|--|| Workshop            : "plant"
    Workshop }|--|| Factory        : "plant"
    Factory }|--|| Plant        : "plant"
    Routing }|--|| Plant         : "plant"
    Routing }|--|| Material           : "material_number_sap"
    RoutingDetail }|--|| Routing    : "routing_key"
    RoutingDetail }|--|| Workshop   : "work_center"
    StageMember }|--|| Factory     : "planWorkshop"
    StageMember }|--|| Workshop     : "workshopCode"
    StageMember }|--|| MemberGroup  : "group"
    Material ||--o{ ProductionVersion : productionVersions

    ProductionVersion ||--|| Routing : routing
    ProductionVersion ||--|| BOM : bom
    ProductionVersion ||--|| Routing: group_counter
    ProductionVersion ||--|| BOM: alternative_bom

    ProductionOrderComponent }|--|| ProductionOrder : productionOrder
    ProductionOrder ||--|{ SettlementRule : settlementRules
    ProductionOrder }|--|| ProductionVersion : productionVersion
    ProductionVersion ||--|{ ProductionOrder: "production_version_code"
    ProductionOrder }|--|| Plant : "plant_code"
    ProductionOrder }|--|| Material : "material_code"
    ProductionOrder }|--|| User : "approved_by"
    ProductionComponent }|--|| ProductionOrder : "production_order_code"

    ProductionComponent }|--|| Material : "material_code"
    ProductionComponent }|--|| Unit : "unit"
    ProductionComponent }|--|| Plant : "plant"
    ProductionComponent }|--|| StorageLocation : "storage_location"

    %% -------------------------------
    %% 5. Logistics Domain (Shipment/Package)
    %% -------------------------------
    Shipment }|--|| Project         : "project_id"
    Shipment }|--|| Workshop        : "warehouse"
    Package }|--|| Shipment         : "shipment_id"

    %% -------------------------------
    %% 6. Member/Stage/Part Domain
    %% -------------------------------
    MemberCategoryStage }|--|| MemberCategory : "category"
    MemberCategoryStage }|--|| Stage : "category"
    Member }|--|| ProductionOrder: "production_order_code"
    Member }|--|| MemberCategory    : "category"
    Member }|--|| MemberType        : "type"
    Member ||--|{ StageMember       : "member"
    Member }|--|| MemberLifeState   : "life_state"
    Member }|--|| Phase             : "phase"
    Member }|--|| Package           : "package"

    Phase }|--|| Zone               : "zone"
    Phase }|--|| MemType            : "member_type"
    Part }|--|| Member              : "member"

    Stage }|--|| StageMember        : "stageCode"
%%    Part }|--|| User                : "cutting_plan_user"
%%    Part }|--|| User                : "cutting_user"
%%    Part }|--|| Workshop            : "cutting_workshop"
%%    Part }|--|| Workshop            : "cutting_plan_workshop"
%%    Part }|--|| User                : "delivery_user"
%%    Part }|--|| MemberType             : "type_id"
    %% -------------------------------
    %% 7. Finance / Assets Domain
    %% -------------------------------
    Assets }|--|| Company           : "basic_unit_code"
    Assets }|--|| ChartOfAccounts   : "asset_account"
    Assets }|--|| ChartOfAccounts   : "debit_account"
    Assets }|--|| ChartOfAccounts   : "credit_account"
    Assets }|--|| Department        : "management_department"

    %% -------------------------------
    %% 8. User/Employee Domain
    %% -------------------------------
    User }|--|| Employee            : "staff_code"
