---
title: Business Partner
config:
  layout: elk
---
erDiagram
    direction lr

    business_partner {
        business_partner_id BigInteger PK
        business_partner_group_id BigInteger FK
        region_id BigInteger FK
        country_id BigInteger FK
    }
    business_partner_group {
        business_partner_group_id BigInteger PK
    }
    customer {
        customer_id BigInteger PK
        business_partner_id BigInteger FK
    }
    customer_accounting_data {
        customer_accouting_data_id BigInteger PK
        customer_id BigInteger FK
        company_code_id BigInteger FK
        reconciliation_account BigInteger FK
        payment_method_id BigInteger FK
        payment_term_id BigInteger FK
    }
    customer_sales_data {
        customer_sales_data_id BigInteger PK
        customer_id BigInteger FK
        sales_org_id BigInteger FK
        distribution_channel_id BigInteger FK
        division_id BigInteger FK
        sales_office_id BigInteger FK
        sales_group_id BigInteger FK
        currency_id BigInteger FK
        account_assignment_group_id BigInteger FK
        delivery_plant BigInteger FK
        customer_group_1 BigInteger FK
        customer_group_2 BigInteger FK
    }
    customer_group {
        customer_group_id BigInteger PK
    }
    sales_group {
        sales_group_id BigInteger PK
    }
    sales_office {
        sales_office_id BigInteger PK
    }
    vendor {
        vendor_id BigInteger PK
        business_partner_id BigInteger FK


    }
    vendor_accounting_data {
        vendor_accounting_data_id BigInteger PK
        vendor_id BigInteger FK
        company_code_id BigInteger FK
        reconciliation_account_id BigInteger FK
        payment_method_id BigInteger FK
        payment_term_id BigInteger FK
        planning_group_id BigInteger FK
    }
    vendor_purchasing_data {
        vendor_purchasing_data_id BigInteger PK
        vendor_id BigInteger FK
        purchasing_org_id BigInteger FK
        sales_person BigInteger FK
        order_currency BigInteger FK
    }
    
    business_partner_bank_account {
        business_partner_bank_account_id BigInteger PK
        business_partner_id BigInteger FK
        bank_key_id BigInteger FK
        country_id BigInteger FK
    }

    counterparty {
        counterparty_id BigInteger PK
        business_partner_id BigInteger FK
    }
    counterparty_company_code_data {
        counterparty_company_code_data_id BigInteger PK
        counterparty_id BigInteger FK
        company_code_id BigInteger FK
    }

    %% BUSINESS PARTNER ENHANCED
    business_partner ||--o| customer : "businessPartner"
    business_partner ||--o| vendor : "businessPartner"
    business_partner ||--o| employee : "businessPartner"
    business_partner ||--o| counterparty : "businessPartner"
    business_partner_group ||--o{ business_partner : "businessPartnerGroup"

    %% VENDOR ENHANCED
    vendor ||--|{ vendor_purchasing_data : "vendor"
    vendor_purchasing_data }o--||  purchasing_org  : "purchasingOrg"
    vendor_purchasing_data }o--o| employee: "salesPerson"
    vendor ||--|{ vendor_accounting_data : "vendor"
    vendor_accounting_data }o--|| GlAccount: "reconciliationAccount"
    vendor_accounting_data }o--o| payment_term: "paymentTerm"
    vendor_accounting_data }o--o| payment_method: "paymentMethod"
    vendor_accounting_data }o--|| planning_group: "planningGroup"
    company_code ||--o{ vendor_accounting_data : "companyCode"

    counterparty ||--o{ counterparty_company_code_data : "counterparty"
    company_code ||--o{ counterparty_company_code_data : "companyCode"

    %% CUSTOMER ENHANCED
    company_code ||--|{ customer_accounting_data : "companyCode"
    customer ||--|{ customer_accounting_data  : "customer"
    customer_accounting_data }|--|| GlAccount: "reconciliationAccount"
    customer_accounting_data }o--o| payment_term: "paymentTerm"
    customer_accounting_data }o--o| payment_method: "paymentMethod"
    customer ||--|{ customer_sales_data : "customer"
    customer_sales_data }o--|| sales_org : "salesOrg"
    customer_sales_data }o--|| distribution_channel : "distributionChannel"
    customer_sales_data }o--|| division : "division"
    customer_sales_data }o--|| sales_office : "salesOffice"
    customer_sales_data }o--|| sales_group : "salesGroup"
    customer_sales_data }o--o| plant : "deliveryPlant"
    customer_sales_data }o--|| tax_classification : "taxClassification"
    customer_sales_data }|--|| customer_group : "customerGroup1"
    customer_sales_data }|--|| customer_group : "customerGroup2"

    %% BANK DETAILS
    business_partner ||--o{ business_partner_bank_account : "businessPartner"
    bank_key ||--o{ business_partner_bank_account : "bankKey"
    company_code ||--|{ house_bank : "companyCode"
    house_bank }o--|| bank_key : "bankKey"
    house_bank ||--o{ account_bank : "houseBank"
