---
title: Material
config:
  layout: elk
---
erDiagram
    direction lr

    material {
        material_id BigInteger PK
        material_type_id BigInteger FK   
        material_group_id BigInteger FK   
        base_unit_id BigInteger FK   
        weight_unit_id BigInteger FK   
        volume_unit_id BigInteger FK   
        manufacturer_id BigInteger FK
        origin_id BigInteger FK
        brand_id BigInteger FK
    }
    material_type {
        material_type_id BigInteger PK
        item_account_code BigInteger FK   
    }
    material_group {
        material_group_id BigInteger PK
        material_type_id BigInteger FK
    }
    classification_class {
        classification_class_id BigInteger PK
    }
    characteristic {
        characteristic_id BigInteger PK
    }
    material_batch {
        material_batch_id BigInteger PK
        material_id BigInteger FK   
        classification_class_id BigInteger FK
        manufacturer_id BigInteger FK
        origin_id BigInteger FK
        brand_id BigInteger FK
        batch_number Varchar
    }
    classification_class_characteristic {
        classification_class_characteristic_id BigInteger PK
        classification_class_id BigInteger FK   
        characteristic_id BigInteger FK   
    }
    material_characteristic_value {
        material_id BigInteger FK
        material_batch_id BigInteger FK
        characteristic_id BigInteger FK
    }
    material_alternative_unit {
        material_alternative_unit_id BigInteger PK
        material_id BigInteger FK
        unit_id BigInteger FK
    }
    material_plant_assignment {
        material_plant_id BigInteger PK
        plant_id BigInteger FK
        material_id BigInteger FK
    }
    material_purchasing_data {
        material_purchasing_data_id BigInteger PK
        material_plant_id BigInteger FK
        order_unit_id BigInteger FK
        purchasing_group_id BigInteger FK
    }
    material_mrp_data {
        material_mrp_data_id BigInteger PK
        material_plant_id BigInteger FK
        mrp_controller BigInteger FK
    }
    material_accounting_data {
        material_accounting_data_id BigInteger PK
        material_plant_id BigInteger FK
        valuation_class_id BigInteger FK
    }
    valuation_class {
        valuation_class_id BigInteger PK
        gl_account_id BigInteger FK
    }
    material_storage_location_data {
        material_storage_location_data_id BigInteger PK
        material_plant_id BigInteger FK
        storage_location_id BigInteger FK
        unit_of_issue_id BigInteger FK
    }
    material_sales_data {
        material_sales_data_id BigInteger PK
        sales_org_id BigInteger FK
        distribution_channel_id BigInteger FK
        division_id BigInteger FK
        material_id BigInteger FK
        sales_unit_id BigInteger FK
        account_assignment_group_id BigInteger FK
    }
    material_tax_data {
        material_tax_data_id BigInteger PK
        material_purchasing_data_id BigInteger FK
        material_sales_data_id BigInteger FK
        tax_category_id BigInteger FK
        tax_classification_id BigInteger FK
    }
    purchasing_info_record {
        purchasing_info_record_id BigInteger PK
        purchasing_org_id BigInteger FK
        material_id BigInteger FK
        vendor_id BigInteger FK
        plant_id BigInteger FK
        price_unit_id BigInteger FK
        order_unit_id BigInteger FK
        tax_code_id BigInteger FK
    }
    unit {
        unit_id BigInteger PK
    }
    employee {
        human_resource erd
    }
    

    %% MATERIAL MASTER
    material }o--|| material_type : "materialType"
    material }o--|| material_group : "materialGroup"
    material }o--|| unit: "baseUnit"
    material }o--|| unit: "weightUnit"
    material }o--|| unit: "volumeUnit"
    material ||--o{ material_alternative_unit : "material"
    material_alternative_unit }o--|| unit: "alternativeUnit"
    
    %% MATERIAL PLANT
    plant ||--o{ material_plant_assignment: "plant"
    material ||--o{ material_plant_assignment : "material"
    employee ||--o{ material_mrp_data  : "mrpController"
    
    material_plant_assignment ||--o| material_purchasing_data : "materialPlant"
    material_plant_assignment ||--o| material_mrp_data: "materialPlant"
    material_plant_assignment ||--o| material_storage_location_data: "materialPlant"
    material_plant_assignment ||--o| material_accounting_data: "materialPlant"
    material_accounting_data }o--|| valuation_class: "valueationClass"
    material_type ||--|| valuation_class: "valuationClass"
    valuation_class |o--|| gl_account: "glAccount"

    material_purchasing_data }o--|| unit: "orderUnit"
    material_purchasing_data }o--|| purchasing_group: "purchasingGroup"
    material_purchasing_data ||--o{ material_tax_data: "materialPurchasingData"
    
    material_storage_location_data }o--||  storage_location: "storageLocation"
    material_storage_location_data }o--||  unit: "issueUnit"
    
    %% MATERIAL SALES
    sales_org ||--o{ material_sales_data: "salesOrg"
    distribution_channel ||--o{ material_sales_data: "distributionChannel"
    division ||--o{ material_sales_data: "division"
    material ||--o{ material_sales_data : "material"
    material_sales_data }o--|| unit: "salesUnit"
    material_sales_data ||--o{ material_tax_data: "materialSalesData"
    material_tax_data }o--|| tax_category: "taxCategory"
    material_tax_data }o--|| tax_classification: "taxClassification"
    
    %% MATERIAL CLASSIFICATION
    classification_class ||--o{ classification_class_characteristic: "classsification_class"
    characteristic ||--o{ classification_class_characteristic: "characteristic"
    material ||--o{ material_batch: "materialBatch"
    material_batch }o--|| classification_class: "batchClass"
    material ||--o{ material_characteristic_value: "material"
    material_batch ||--o{ material_characteristic_value: "value"
    characteristic ||--o{ material_characteristic_value: "characteristic"
    
    %% PURCHASING INFO RECORD
    %% purchasing_group |o--o{ purchasing_info_record: "purchasingGroup"
    material ||--o{ purchasing_info_record: "material"
    vendor ||--o{ purchasing_info_record: "vendor"
    plant |o--o{ purchasing_info_record: "plant"
    purchasing_org ||--o{ purchasing_info_record: "purchasingOrg"
    purchasing_info_record }o--|| unit : "priceUnit"
    purchasing_info_record }o--|| unit : "orderUnit"

    origin {
        origin_id BigInteger PK
    }
    brand {
        brand_id BigInteger PK
    }
    manufacturer {
        manufacturer_id BigInteger PK
    }
    
    material }o--|| origin: "origin"
    material }o--|| brand: "brand"
    material }o--|| manufacturer: "manufacturer"

    material_batch }o--|| origin: "origin"
    material_batch }o--|| brand: "brand"
    material_batch }o--|| manufacturer: "manufacturer"
    purcasing_org ||--o{ purchasing_group: "purchasingOrg"