---
title: sap_s4hana_master_entities (s4hana_compliant)
config:
  layout: elk
---
erDiagram
    direction lr

    business_partner {
        business_partner_id BigInteger PK
        business_partner_group_id BigInteger FK
        region_id BigInteger FK
        country_id BigInteger FK
    }
    business_partner_group {
        business_partner_group_id BigInteger PK
    }
    customer {
        customer_id BigInteger PK
        business_partner_id BigInteger FK
    }
    customer_accounting_data {
        customer_accouting_data_id BigInteger PK
        customer_id BigInteger FK
        company_code_id BigInteger FK
        reconciliation_account BigInteger FK
        payment_method_id BigInteger FK
        payment_term_id BigInteger FK
    }
    customer_sales_data {
        customer_sales_data_id BigInteger PK
        customer_id BigInteger FK
        sales_area_id BigInteger FK
        sales_office_id BigInteger FK
        sales_group_id BigInteger FK
        currency_id BigInteger FK
        account_assignment_group_id BigInteger FK
        delivery_plant BigInteger FK
        customer_group_1 BigInteger FK
        customer_group_2 BigInteger FK
    }
    customer_group {
        customer_group_id BigInteger PK
    }
    sales_group {
        sales_group_id BigInteger PK
    }
    sales_office {
        sales_office_id BigInteger PK
    }
    vendor {
        vendor BigInteger PK
        business_partner_id BigInteger FK


    }
    vendor_accounting_data {
        vendor_accounting_data_id BigInteger PK
        vendor_id BigInteger FK
        company_code_id BigInteger FK
        reconciliation_account_id BigInteger FK
        payment_method_id BigInteger FK
        payment_term_id BigInteger FK
        planning_group_id BigInteger FK
    }
    vendor_purchasing_data {
        vendor_purchasing_data_id BigInteger PK
        vendor_id BigInteger FK
        purchasing_org_id BigInteger FK
        sales_person BigInteger FK
        order_currency Big FK
    }
    
    business_partner_bank_account {
        business_partner_bank_account_id BigInteger PK
        business_partner_id BigInteger FK
        bank_key_id BigInteger FK
        country_id BigInteger FK
    }

    %% BUSINESS PARTNER ENHANCED
    business_partner ||--|| customer : "customer"
    business_partner ||--|| vendor : "vendor"
    business_partner ||--|| employee : "employee"
    business_partner_group ||--|{ business_partner : "businessPartner"

    %% VENDOR ENHANCED
    vendor ||--|{ vendor_purchasing_data : "purchasingData"
    vendor_purchasing_data }|--||  purchasing_org  : "purchasingOrg"
    vendor_purchasing_data  }|--|| purchasing_group  : "purchasingGroup"
    vendor_purchasing_data }|--|| employee: "sales_person"
    vendor ||--|{ vendor_accounting_data : "accountingData"
    vendor_accounting_data }|--|| GlAccount: "reconciliationAccount"
    vendor_accounting_data }|--|| payment_term: "paymentTerm"
    vendor_accounting_data }|--|| payment_method: "paymentMethod"
    vendor_accounting_data }|--|| planning_group: "planning_group"
    company_code ||--|{ vendor_accounting_data : "companyCode"

    %% CUSTOMER ENHANCED
    company_code ||--|{ customer_accounting_data : "companyCode"
    customer ||--|{ customer_accounting_data  : "customer"
    customer_accounting_data }|--|| GlAccount: "reconciliationAccount"
    customer_accounting_data }|--|| payment_term: "paymentTerm"
    customer_accounting_data }|--|| payment_method: "paymentMethod"
    customer ||--|{ customer_sales_data : "salesData"
    customer_sales_data }|--|| sales_office : "salesOffice"
    customer_sales_data }|--|| sales_group : "salesGroup"
    customer_sales_data }|--|| plant : "plant"
    customer_sales_data }|--|| sales_area : "salesArea"
    customer_sales_data }|--|| account_assignment_group : "accountAssignmentGroup"
    customer_sales_data }|--|| customer_group : "customerGroup1"
    customer_sales_data }|--|| customer_group : "customerGroup2"

    %% BANK DETAILS
    business_partner ||--|{ business_partner_bank_account : "bankAccount"
    bank_key ||--|{ business_partner_bank_account : "bankKey"
    company_code ||--|{ house_bank : "houseBank"
    house_bank }|--|| bank_key : "bankKey"
    house_bank ||--|{ account_bank : "accountBank"
