---
title: Organization Structure
config:
  layout: elk
---
erDiagram
    direction lr company_code {
        company_code_id BigInteger PK
        coa_id BigInteger FK
        country_id BigInteger FK
        currency_id BigInteger FK
        fiscal_variant_id BigInteger FK        
        posting_period_variant_id BigInteger FK        
    }
    fiscal_year_variant {
        fiscal_year_variant BigInteger PK
    }
    posting_period_variant {
        posting_period_variant BigInteger PK
    }
    plant {
        plant_id BigInteger PK
        company_code_id BigInteger FK
        country_id BigInteger FK
    }
    storage_location {
        storage_location_id BigInteger PK
        plant_id BigInteger FK
    }
    sales_org {
        sales_org_id BigInteger PK
        company_code_id BigInteger FK
    }
    distribution_channel {
        distribution_channel_id BigInteger PK
    }
    division {
        division_id BigInteger PK
    }
    sales_area {
        sales_org_id BigInteger FK
        distribution_channel_id BigInteger FK
        division_id BigInteger FK
    }
    purchasing_org {
        purchasing_org_id BigInteger PK
        company_code_id BigInteger FK
    }
    purchasing_group {
        purchasing_group_id BigInteger PK
        purchasing_org_id BigInteger FK
    }

    company_code ||--|{ project : "company_code"
    project ||--|{ wbs : "project"
    wbs ||--|{ wbs : "parentWBS"

    %% ORGANIZATIONAL STRUCTURE
    company_code ||--|{ plant : "companyCode"
    plant ||--|{ storage_location : "plant"

    %% PROFIT CENTER COST CENTER
    company_code }|--|| coa: "coa"
    company_code ||--|{ cost_center: "companyCode"
    company_code ||--|{ profit_center: "companyCode"
    profit_center ||--|{ cost_center: "profitCenter"
    cost_center ||--|{ work_center: "costCenter"
    
    %% SALES ORGANIZATION
    company_code ||--|| sales_org: "companyCode"
    sales_org ||--|{ sales_area: "salesOrg"
    distribution_channel ||--|{ sales_area: "distributionChannel"
    division ||--|{ sales_area: "division"
    
    %% PURCHASING ORGANIZATION
    company_code ||--|| purchasing_org: "companyCode"
    purchasing_org ||--|{ purchasing_group: "purchasingOrg"
    
    %% FI CONFIGURATION (Organization related)
    fiscal_year_variant ||--|{ company_code : "fiscalVariant"
    posting_period_variant ||--|{ company_code : "postingPeriodVariant"
