---
title: HRM Master Entities
config:
  layout: elk
---
erDiagram
Direction LR
    %% ==== ENTITY CHÍNH ====
    NhanVien ||--|| ThongTinLienLac : lienLac
    NhanVien ||--|{ QuyetDinhNhanSu : quyetDinh
    NhanVien ||--o| TaiKhoan : taiKhoan
    NhanVien ||--|{ TrinhDo : trinhDo
    NhanVien ||--o| Thue : quyetToan
    NhanVien ||--o| BaoHiem : baoHiem
    NhanVien ||--o{ ChamCong : chamCong
    NhanVien ||--o{ HopDong : "hopDong"
    NhanVien ||--o{ Luong : "luong"
    NhanVien ||--o| DanhMucNhomMau : "nhomMau"

    Luong o{--|| DanhMucDoiTuongOT : "doiTuongOT"

    ThongTinLienLac ||--|| DiaChi : diaChiThuongTru
    ThongTinLienLac ||--|| DiaChi : diaChiHienTai
    ThongTinLienLac ||--|| DanhMucTinhThanh : nguyenQuan
    ThongTinLienLac ||--|| DanhMucTinhThanh : noiSinh
    ThongTinLienLac ||--|| DanhMucTinhThanh : noiCapCCCD

 
    %% ==== LIÊN KẾT DANH MỤC ====
    NhanVien }o--o| DanhMucGioiTinh : gioiTinh
    NhanVien }o--o| DanhMucHonNhan : honNhan
    NhanVien }o--|| DanhMucQuocTich : quocTich
    NhanVien }o--|| DanhMucTrangThaiLaoDong : trangThai

    DiaChi ||--|| DanhMucPhuongXa: phuongXa
    TaiKhoan |o--|| DanhMucNganHang : nganHang
    DanhMucCaLamViec }o--|| DanhMucNhomCa : nhomCa

    QuyetDinhNhanSu }o--o| DanhMucPhanLoaiChiPhi: chiPhiCap1
    QuyetDinhNhanSu }o--o| DanhMucPhanLoaiChiPhi: chiPhiCap2

    NhanVien_NgoaiNgu }o--|| DanhMucNgoaiNgu : thuoc
    NhanVien_NgoaiNgu }o--|| NhanVien : thuoc
 
    QuyetDinhNhanSu }o--|| DanhMucPhongBan : phongBan
    QuyetDinhNhanSu }o--|| DanhMucViTri : viTri
    QuyetDinhNhanSu }o--|| DanhMucCapBac : capBac
    QuyetDinhNhanSu }o--o| DanhMucLoaiNhanVien : thuocLoai
    QuyetDinhNhanSu }o--|| DanhMucChucDanh : chucDanh
    QuyetDinhNhanSu }o--|o NhanVien: quanLyTrucTiep
 
    TrinhDo }o--o| DanhMucTrinhDo : trinhDo
    TrinhDo }o--o| DanhMucTruongHoc : truong
    TrinhDo }o--o| DanhMucNganhHoc : nganhHoc
    TrinhDo }o--o| DanhMucChuyenNganh : chuyenNganh
 
    BaoHiem }o--|| DanhMucNoiKCB : kham
 
    ChamCong }|--|| DanhMucCaLamViec : caLamViec
    ChamCong }|--|| DanhMucMayChamCong : mayChamCong
    ChamCong }|--|| DanhMucDoiTuongChamCong : doiTuongChamCong

    HopDong ||--|| DanhMucLoaiHopDong : "loaiHD"

    DanhMucTinhThanh ||--o{ DanhMucQuanHuyen : "quanHuyen"
    DanhMucQuanHuyen ||--o{ DanhMucPhuongXa : "phuongXa"
 
    %% ==== THỰC THỂ CHÍNH ====
    NhanVien {
        maNhanVien Text PK
        maGioiTinh Text FK
        maHonNhan Text FK
        maQuocTich Text FK
        maTrangThaiLaoDong Text FK
        hoTen Text
        tenThuongGoi Text
        ngaySinh date
        ngayBatDauLam date
        ngayChinhThuc date
        ngayTinhThamNien date
        soNgayTruThamNien Number
    }
 
    ThongTinLienLac {
        maNhanVien Text FK
        diaChiHienTai Text FK
        diaChiThuongTru Text FK
        nguyenQuan Text FK
        noiSinh Text FK
        noiCapCCD Text FK
        nhomMau Text FK
        soCCCD Text
        ngayCapCCCD date
        dienThoai Text
        emailCongTy Text
        emailCaNhan Text
        lienHeKhanCap Text
        sdtLienHeKhanCap Text
    }
 
    QuyetDinhNhanSu {
        maNhanVien Text FK
        maPhongBan Text FK
        maViTri Text FK
        maCapBac Text FK
        maNhanVienQuanLyTrucTiep Text FK        
        loaiNhanVien Text FK
        chucDanh Text FK
        chiPhiCap1 Text FK
        chiPhiCap2 Text FK
        soQuyetDinh Text
        ngayQuyetDinh date
    }
 
    TaiKhoan {
        maNhanVien Text PK, FK        
        maNganHang Text FK
        taiKhoanNganHang Text
        chiNhanh Text
        maSoThue Text
    }
 
    TrinhDo {
        maNhanVien Text FK
        maNganhHoc Text FK
        maChuyenNganh Text FK
        maTrinhDoHocVan Text FK
        maTruongHoc Text FK
    }

    NhanVien_NgoaiNgu {
        maNhanVien Text FK
        maNgoaiNgu Text FK
        trinhDo Text
    }
 
    Thue {
        maNhanVien Text PK, FK
        uyQuyen boolean
        khongTinhGiamTru boolean
    }
 
    BaoHiem {
        maNhanVien Text PK, FK
        maNoiKCB Text FK
        ngayNghiViec date
        soSoBHXH Text
        maBHXH Text
        theBHYT Text
        ngayCapTheBHYT date
        ngayHetHanBHYT date
    }

    Luong {
        maLuong Text PK
        maNhanVien Text FK
        maDoiTuongOT Text FK
        luongCoBan decimal
        phuCap decimal
        heSoLuong decimal
        ngayHieuLuc date
    }

    DiaChi {
        maDiaChi Text PK
        maPhuongXa Text FK
        soDuong Text
    }
 
    HopDong {
        maHopDong Text PK
        maNhanVien Text FK
        maLoaiHopDong Text FK
        soHopDong Text
        ngayBatDau date
        ngayKetThuc date
    }
    
    ChamCong {
        maNhanVien Text FK
        maDoiTuongChamCong Text FK
        maCaLamViec Text FK
        ngayChamCong date
    }
    %% ==== DANH MỤC ====
    DanhMucTinhThanh {
        maTinhThanh Text PK

    }

    DanhMucTrangThaiLaoDong {
        maTrangThaiLaoDong Text PK
        ten Text
    }

    DanhMucLoaiHopDong {
        maLoaiHopDong Text PK
        ten Text
    }

    DanhMucGioiTinh {
        maGioiTinh Text PK
        ten Text
    }
 
    DanhMucHonNhan {
        maHonNhan Text PK
        ten Text
    }
 
    DanhMucQuocTich {
        maQuocTich Text PK
        ten Text
    }
 
    DanhMucPhongBan {
        maPhongBan Text PK
        ten Text
    }
 
    DanhMucViTri {
        maViTri Text PK
        ten Text
    }
 
    DanhMucCapBac {
        maCapBac Text PK
        ten Text
    }
    
    DanhMucChucDanh {
        Text maChucDanh PK
        Text ten
    }
 
    DanhMucTrinhDo {
        maTrinhDo Text PK
        ten Text
    }
 
    DanhMucTruongHoc {
        maTruongHoc Text PK
        ten Text
    }
 
    DanhMucNganhHoc {
        maNganhHoc Text PK
        ten Text
    }
 
    DanhMucChuyenNganh {
        maChuyenNganh Text PK
        ten Text
    }
 
    DanhMucNgoaiNgu {
        maNgoaiNgu Text PK
        ten Text
    }
 
    DanhMucNoiKCB {
        maNoiKCB Text PK
        ten Text
    }
 
    DanhMucNhomCa {
        maNhomCa Text PK
        ten Text
    }


    DanhMucTinhThanh {
        Text maTinhThanh PK
        Text ten
        Text ghiChu
    }

    DanhMucQuanHuyen {
        Text maQuanHuyen PK
        Text maTinhThanh FK
        Text ten
    }

    DanhMucPhuongXa {
        Text maPhuongXa PK
        Text maQuanHuyen FK
        Text ten
    }

    DanhMucPhanLoaiChiPhi {
        Text maLoaiChiPhi PK
        Text ten
    }

    DanhMucNganHang {
        Text maNganHang PK
        Text ten
        Text tenVietTat
    }

    DanhMucCaLamViec {
        Text maCa PK
        Text tenCa
        time gioBatDau
        time gioKetThuc
    }

    DanhMucMayChamCong {
        Text maMay PK
        Text ten
        Text diaChiIP
        Text viTri
    }

    DanhMucDoiTuongChamCong {
        Text maDoiTuong PK
        Text ten
    }

    DanhMucDoiTuongOT {
        Text maDoiTuongOT PK
        Text ten
    }

    DanhMucLoaiNhanVien {
        Text maLoaiNhanVien PK
        Text ten
    }

    DanhMucNhomMau {
        Text maNhomMau PK
        Text ten
    }