---
config:
  theme: neutral
  layout: elk
---
erDiagram
Direction LR
 
    NganSach {
        maNganSach Text PK
        ten Text
    }

    LoaiNganSach {
        maLoaiNganSach Text PK
        ten Text
    }
    
    KhoanMucKeToan {
        maKhoanMucKeToan Text PK
        ten Text
    }

    NganSach_DuAn {
        maDuAn Text FK
        maNganSach Text FK
        maKhoanMucKeToan Text FK
        donVi Text
        soLuong Number
        donGia Number
        maKhoanMucKeToan Text        
    }

    DuAn {
        maDuAn Text PK
        maKhachHang Text FK
        ten Text
        ngayBatDau date
        ngayKetThuc date
    }

    HangMuc {
        maHangMuc Text PK
        maDuAn Text FK
        maLoaiHinhSanPham Text FK
        ten Text
    }

    PR {
        maPR Text PK
        maDiaChiGiaoHang Text FK
        maHangMuc Text FK
        maNhanVienDeNghi Text FK
        maNhanVienPheDuyet Text FK
        trangThai Text
        ngayTao date
        ngayDuyet date
    }

    PRChiTiet {
        maVatTu Text FK
        maPR Text FK
        soLuong Number
    }

    PO {
        maPO Text PK
        maBoPhanLapDonHang Text FK
        maNhanVienLapDonHang Text FK
        maNhanVienPheDuyet Text FK
        trangThai Text
        ngayTao date
        ngayDuyet date
        ngayGiaoHangDuKien date
    }

    POChiTiet {
        maPO Text PK
        maPR Text FK
        maNCC Text FK
        maNganSach Text FK
        soLuong Number
        donGia Number
    }


    BOM {
        maBOM Text PK
        phienBan Number
        ten Text
    }    

    BOMChiTiet {
        maBOM Text PK
        maHangMuc Text FK
        maVatTu Text FK
        soLuong Number
        haoHut Number
    }

    VatTu {
        maVatTu Text PK
        maDonViTinh Text FK
        maNhomHang Text FK
        maLoaiHinhSanPham Text FK
        maTaiKhoanKeToan Text FK
        maPhanCapVatTu1 Text FK
        maPhanCapVatTu2 Text FK
        ten Text        
    }

    PhanCapVatTu {
        maCayPhanCapVatTu Text PK
        maNhomCha Text FK
        ten Text
    }

    TinhChatVatTu {
        maTinhChatVatTu Text PK
        ten Text
    }

    LoaiHinhSanPham {
        maLoaiHinhSanPham Text PK
        ten Text
    }

    TaiKhoanKeToan {
        maTaiKhoanKeToan Text PK
        ten Text
    }

    ThueGTGT {
        maThueGTGT Text PK
        tenThue Text
        loaiThue Text
    }

    TaiKhoanKeToan_ThueGTGT {
        maTaiKhoanKeToan Text FK
        maThueGTGT Text FK
    }

    DangKyTaiSan {
        maDangKyTaiSan Text PK
        maTaiKhoanNguyenGia Text FK
        maTaiKhoanKH Text FK
        maTaiKhoanHangBan Text FK
        maDonViTinh Text FK
        maBoPhan Text FK
    }

    BoPhan {
        maBoPhan Text PK
        ten Text
    }

    DonViTinh {
        maDonViTinh Text PK
        ten Text
    }

    NhomHang {
        maNhomHang Text PK
        maTaiKhoanTonKho Text FK
        maTaiKhoanGiaVon Text FK
        maTaiKhoanDoanhThu Text FK
        maTaiKhoanHangBan Text FK
        ten Text
    }

    YeuToVatTu {
        maYeuToVatTu Text PK
        ten Text
    }

    VatTu_TinhChatVatTu {
        maVatTu Text FK
        maTinhChatVatTu Text FK
    }

    "DoiTuong_KH&NCC" {
        maDoiTuong Text PK
        ten Text
    }

    DiaChiGiaoHang {
        maDiaChiGiaoHang Text PK
        diaChi Text
    }

    NhanVien {
        maNhanVien Text PK
        ten Text
    }

    LenhNhapKho {
        maLenhNhapKho Text PK
        maKho Text FK
        maPO Text FK
        ngayTao date
        ngayDuyet date
        trangThai Text
    }

    PhieuNhapKho {
        maPhieuNhapKho Text PK
        maLenhNhapKho TextFK        
        maKho Text FK
    }

    LenhXuatKho {
        maLenhNhapKho Text PK
        maKho Text FK
        ngayTao date
        ngayDuyet date
        trangThai Text
    }

    PhieuXuatKho {
        maPhieuXuatKho Text PK
        maLenhXuatKho Text FK
        maKho Text FK
    }

    LenhXuatKhoChiTiet {
        maLXK Text PK
        maVatTu Text FK
        soLuong Number
    }

    PhieuNhapKhoChiTiet {
        maPNK Text PK
        maVatTu Text FK
        soLuong Number
    }

    LenhNhapKhoChiTiet {
        maLNK Text PK
        maVatTu Text FK
        soLuong Number
    }

    PhieuXuatKhoChiTiet {
        maPXK Text PK
        maVatTu Text FK
        soLuong Number
    }

    
    __Kho {
        maKho Text PK
        ten Text
    }

    TonKho {
        maKho Text PK
        maVatTu Text FK
        soLuong Number
    }
 
    %% Relationships
    LoaiNganSach ||--o{ NganSach : "loai"
    NganSach ||--o{ NganSach_DuAn : "phanBo"
    DuAn ||--o{ NganSach_DuAn : "duAn"
    NganSach_DuAn o{--|| KhoanMucKeToan : "khoanMuc"
    DuAn ||--o{ HangMuc : "hangMuc"
    HangMuc ||--o{ PR : "pr"
    PR |{--|| DiaChiGiaoHang : "diaChi"
    PR |{--|| NhanVien : "tao"
    PR |{--o| NhanVien : "duyet"
    PR |{--|| BoPhan : "boPhan"
    PR ||--o{ PRChiTiet : "chiTiet"
    PRChiTiet o{--|| VatTu : "vatTu"
    VatTu ||--|{ BOMChiTiet : "suDung"
    BOM |{--|| BOMChiTiet : "bom"
    HangMuc ||--|| BOMChiTiet : "hangMuc"
    PO ||--o{ POChiTiet : "chiTiet"
    POChiTiet o{--|| "DoiTuong_KH&NCC" : "ncc"
    POChiTiet o{--|| NganSach : "nganSach"
    POChiTiet o{--|| PR : "pr"
    PO ||--|| NhanVien : "tao"
    PO ||--|| BoPhan : "boPhan"
    VatTu o{--|| DonViTinh : "dvt"
    VatTu o{--|| NhomHang : "nhom"
    VatTu o{--|| LoaiHinhSanPham : "loai"
    VatTu ||--|{ YeuToVatTu : "yeuTo"
    VatTu o{--|| TaiKhoanKeToan : "tk"
    VatTu o{--o| PhanCapVatTu : "cap1"
    VatTu o{--o| PhanCapVatTu : "cap2"
    PhanCapVatTu o|--o| PhanCapVatTu : "nhomCha"
    TinhChatVatTu ||--o{ VatTu_TinhChatVatTu : "tinhChat"
    VatTu_TinhChatVatTu o{--|| VatTu : "vatTu"
    NhomHang o{--|| TaiKhoanKeToan : "tkDT"
    NhomHang o{--|| TaiKhoanKeToan : "tkCP"
    NhomHang o{--|| TaiKhoanKeToan : "tkGV"
    NhomHang o{--|| TaiKhoanKeToan : "tkTK"
    TaiKhoanKeToan ||--o{ TaiKhoanKeToan_ThueGTGT : "tk"
    ThueGTGT ||--o{ TaiKhoanKeToan_ThueGTGT : "thue"
    DangKyTaiSan o{--|| TaiKhoanKeToan : "tk"
    DangKyTaiSan |{--|| DonViTinh : "dvt"
    DangKyTaiSan o{--|| BoPhan : "boPhan"
    DangKyTaiSan o{--|| KhoanMucKeToan : "khoanMuc"
    "DoiTuong_KH&NCC" ||--o{ DuAn : "kh"
    __Kho ||--o{ TonKho : "ton"
    __Kho ||--o{ LenhNhapKho : "nhap"
    __Kho ||--o{ LenhXuatKho : "xuat"
    TonKho o{--|| VatTu : "vatTu"
    LenhNhapKho o{--|| PO : "po"
    LenhNhapKho ||--o{ PhieuNhapKho : "phieu"
    LenhXuatKho ||--o{ PhieuXuatKho : "phieu"
    LenhNhapKho ||--|{ LenhNhapKhoChiTiet : "chiTiet"
    PhieuNhapKho ||--|{ PhieuNhapKhoChiTiet : "chiTiet"
    LenhXuatKho ||--|{ LenhXuatKhoChiTiet : "chiTiet"
    PhieuXuatKho ||--|{ PhieuXuatKhoChiTiet : "chiTiet"
    LenhNhapKhoChiTiet o{--|| VatTu : "vatTu"
    PhieuNhapKhoChiTiet o{--|| VatTu : "vatTu"
    LenhXuatKhoChiTiet o{--|| VatTu : "vatTu"
    PhieuXuatKhoChiTiet o{--|| VatTu : "vatTu"