---
title: OVERVIEW - SAP S/4HANA Core Entities
config:
  theme: neutral
  layout: elk
---
erDiagram
direction lr
    
    Unit {
        Text unitCode PK
        Text unitName
    }

    PurchasingInfoRecord {
        Text recordCode PK
        Text vendorName
    }


    Budget {
        Text budgetCode PK
        Text budgetName
    }

    BudgetType {
        Text budgetTypeCode PK
        Text budgetTypeName
    }

    BudgetProject {
        Text projectCode FK
        Text budgetCode FK
        Text glAccountCode FK
        Text unit
        Number qty
        NUmber price
    }

    BudgetType ||--o{ Budget : "type"
    Budget ||--o{ BudgetProject : "phanBo"
    Project ||--o{ BudgetProject : "duAn"
    BudgetProject o{--|| GlAccount : "khoanMuc"


    %% --- Company Structure (FI/CO Foundation) ---
    CompanyCode {
        Text companyCode PK
        Text companyCodeName
        Text controllingAreaCode FK
    }

    ControllingArea {
        Text controllingAreaCode PK
        Text operatingConcernCode FK
        Text controllingAreaName
    }

    Plant {
        Text plantCode PK
        Text companyCode FK
        Text plantName
    }

    SalesOrganization {
        Text salesOrgCode PK
        Text companyCode FK
        Text salesOrgName
    }

    DistributionChannel {
        Text distChannelCode PK
        Text salesOrgCode FK 
        Text distChannelName
    }

    Division {
        Text divisionCode PK
        Text salesOrgCode FK 
        Text divisionName
    }

    SalesArea {
        Text salesAreaCode PK
        Text salesOrgCode FK
        Text distributionChanelCode FK
        Text divisionCode FK
    }

    PurchasingOrganization {
        Text purchOrgCode PK
        Text companyCode FK
        Text purchOrgName
    }

    PurchasingGroup {
        Text purchGroupCode PK
        Text purchOrganizationCode FK
        Text companyCode FK
        Text purchGroupName
    }

    Segment {
        Text segmentCode PK
        Text segmentName
    }

    SalesOffice {
        Text salesOfficeCode PK
        Text salesOrgCode FK
        Text salesOfficeName 
    }

    CompanyCode }|--|| ControllingArea : controllingArea
    CompanyCode ||--o{ Plant : plants
    CompanyCode ||--o{ SalesOrganization : salesOrganizations
    CompanyCode ||--o{ PurchasingOrganization : purchasingOrganizations

    Plant ||--o{ StorageLocation : storageLocations
    Plant ||--o{ WorkCenter : workCenters

    SalesOrganization ||--o{ SalesOffice : salesOffices
    SalesOrganization ||--o{ DistributionChannel : distributionChannels
    SalesOrganization ||--o{ Division : divisions
    SalesOrganization ||--o{ SalesArea : salesAreas

    DistributionChannel ||--o{ SalesArea : salesAreas
    Division ||--o{ SalesArea : salesAreas

    PurchasingOrganization ||--o{ PurchasingGroup : purchasingGroups
    PurchasingOrganization ||--o{ Plant : responsiblePlants

    %% BUSINESS PARTNER
    CustomerGroup {
        Text groupCode PK
        Text groupName
    }

    BusinessPartner {
        Text bpCode PK
        Text bpCategory
        Text bpName
    }

    Customer {
        Text customerCode PK
        Text bpCode FK            
        Text salesOrgCode FK      
        Text distChannelCode FK   
        Text divisionCode FK      
        Text paymentTermCode FK   
        Text paymentMethodCode FK 
        Text taxCode FK           
        Text groupCode FK         
        Text levelCode FK         
        Text customerName
    }

    Supplier {
        Text supplierCode PK
        Text bpCode FK            
        Text purchOrgCode FK      
        Text paymentTermCode FK   
        Text paymentMethodCode FK 
        Text taxCode FK           
        Text supplierName
    }

    BusinessPartner ||--|| Customer : customer
    BusinessPartner ||--|| Supplier : supplier

    Customer }o--|| SalesOrganization : salesOrganization
    Customer }o--|| DistributionChannel : distributionChannel
    Customer }o--|| Division : division
    Customer }o--|| PaymentTerm : paymentTerm
    Customer }o--|| PaymentMethod : paymentMethod
    Customer }o--|| TaxCode : tax
    Customer }o--|| PlanningGroup : planningGroup
    Customer }o--|| PlanningLevel : planningLevel
    Customer }o--|| CustomerGroup : customerGroup

    Supplier }o--|| PurchasingOrganization : purchasingOrganization
    Supplier }o--|| PaymentTerm : paymentTerm
    Supplier }o--|| PaymentMethod : paymentMethod
    Supplier }o--|| TaxCode : tax
    %% BUSINESS PARTNER

    PurchasingInfoRecord {
        Text materialCode FK
        Text supplierCode FK
        Text purchasingOrgCode FK
        Text infoRecordKey PK
    }

    PurchasingInfoRecord }o--|| Material : material
    PurchasingInfoRecord }o--|| Supplier : supplier
    PurchasingInfoRecord }o--|| PurchasingOrganization : purchasingOrganization

    %% Material 
    Material {
        Text materialCode PK
        Text materialTypeCode FK
        Text materialGroupCode FK
        Text parentMaterialCode FK
        Text storageLocationCode FK
        Text purchasingOrgCode FK
        Text taxCode FK
        Text unitCode FK
        Text wbsElementId FK 
    }
    MaterialType {
        Text materialTypeCode PK
        Text materialTypeName
    }
    MaterialGroup {
        Text materialGroupCode PK
        Text materialGroupName
    }
    MaterialSalesData {
        Text materialCode FK
        Text salesArea FK
    }

    Material }o--|| MaterialType : materialType
    Material }o--|| MaterialGroup : materialGroup
    Material ||--|| Material : parentMaterial
    Material }o--|| StorageLocation : storageLocation
    Material }o--|| PurchasingOrganization : purchasingOrganization
    Material }o--|| Routing : routing
    Material ||--o{ ProductionVersion : productionVersions
    Material ||--|{ ProductionOrderComponent : productionOrders
    Material ||--o{ BOM : bomComponents
    Material ||--|{ MaterialSalesData : salesData
    Material }o--|| WbsElement : wbsElement
    MaterialSalesData }|--|| SalesArea : salesArea

    Material }|--|| Unit: unit
    %% Material 

    %% Production Version 
    ProductionVersion {
        Text productionVersionCode PK
        Text routingCode FK
        Text bomCode FK
    }

    Routing {
        Text routingCode PK
        Text routingName
    }

    BOM {
        Text bomCode PK
        Text description
    }

    ProductionOrderComponent {
        Text materialCode FK
        Text productionOrderCode FK
        Number qty
    }

    ProductionOrderComponent }|--|| ProductionOrder : productionOrder



    ProductionVersion ||--|| Routing : routing
    ProductionVersion ||--|| BOM : bom

    Routing ||--o{ WorkCenter : workCenters

    Operation {
        Text operationCode PK
        Text operationDescription
    }

    Routing ||--|{ Operation : operations

    ProductionOrder {
        Text productionOrderCode PK
        Text CostCenterCode FK
        Text ProfitCenterCode FK
        Text productionOrderDescription
    }

    SettlementRule {
        Text settlementRuleId PK
        Text senderObjectType
        Text senderObjectKey FK
        Text receiverObjectType
        Text receiverObjectKey FK
        Text settlementType
        Number percentage
    }

    ProductionOrder }|--|| ProductionVersion : productionVersion
    ProductionOrder ||--|{ SettlementRule : settlementRules
    WbsElement ||--|{ SettlementRule : receivedSettlementRules
    %% Production Order

    %% Sale
    SalesOrder {
        Text salesOrderCode PK
        Text customerCode FK
        Text companyCode FK
        Text salesAreaCode FK
        Date orderDate
    }
    SalesArea ||--|{ SalesOrder : salesOrders
    Customer ||--|{ SalesOrder : salesOrders
    CompanyCode ||--|{ SalesOrder : salesOrders
    %% Sale


    %% Financial
    ChartOfAccounts {
        Text coaCode PK
        Text coaName
    }

    GlAccount {
        Text glAccountCode PK
        Text coaCode FK             
        Text companyCode FK         
        Text glAccountDescription
    }

    GlAccountTaxCode {
        Text taxCode FK 
        Text glAccount FK
    }

    GlAccount ||--|{ GlAccountTaxCode : tax
    GlAccountTaxCode }|--|| TaxCode: account

    CostElement {
        Text costElementCode PK
        Text glAccountCode FK      
        Text costElementDescription
    }

    CostCenter {
        Text costCenterCode PK
        Text controllingAreaCode FK 
        Text companyCode FK         
        Text plantCode FK           
        Text profitCenterCode FK    
        Text costCenterName
    }

    ProfitCenter {
        Text profitCenterCode PK
        Text controllingAreaCode FK 
        Text companyCode FK         
        Text plantCode FK           
        Text segmentCode FK         
        Text profitCenterName
    }

    ProfitCenter }|--|| Segment : segment
    CostCenter }|--|| Segment : segment

    InternalOrder {
        Text internalOrderCode PK
        Text costCenterCode FK 
        Text wbsElementId FK   
        Text orderDescription
    }
    %% Financial

    Project {
        Text projectId PK
        Text projectName
    }

    WbsElement {
        Text wbsElementId PK
        Text projectId FK
        Text wbsElementDescription
    }

    OperatingConcern {
        Text operatingConcernCode PK
        Text operatingConcernName
    }

    ChartOfAccounts ||--o{ GlAccount : glAccounts
    GlAccount ||--|| CompanyCode : companyCode
    GlAccount ||--o{ CostElement : costElements

    CostCenter }|--|| ControllingArea : controllingArea
    CostCenter }|--|| CompanyCode : companyCode
    CostCenter }|--|| Plant : plant
    CostCenter }|--|| ProfitCenter : profitCenter
    CostCenter ||--o{ Skf : skfs
    CostCenter ||--o{ GlAccount : glAccounts
    CostCenter ||--|{ WorkCenter : workCenters
    CostCenter ||--|{ ActivityType : activityTypes
    WorkCenter ||--|{ ActivityType : activityTypes

    ProfitCenter }|--|| ControllingArea : controllingArea
    ProfitCenter }|--|| CompanyCode : companyCode
    ProfitCenter }|--|| Plant : plant

    InternalOrder ||--|| CostCenter : costCenter
    InternalOrder ||--|| WbsElement : wbsElement

    Project ||--o{ WbsElement : wbsElements

    ControllingArea }|--|| OperatingConcern : operatingConcern

    %% --- Bank & Payment Details ---
    HouseBank {
        Text houseBankId PK
        Text companyCode FK
        Text bankName
    }

    BankAccount {
        Text bankAccountId PK
        Text houseBankId FK
        Text bankKey FK    
        Text accountDescription
    }

    BankKey {
        Text bankKey PK
        Text bankDetails
    }

    PaymentTerm {
        Text paymentTermCode PK
        Text termDescription
    }

    PaymentMethod {
        Text paymentMethodCode PK
        Text methodDescription
    }

    HouseBank ||--o{ BankAccount : bankAccounts
    BankAccount ||--|| BankKey : bankKey
    CompanyCode ||--o{ HouseBank : houseBanks

    %% --- Other Common Master Data ---
    TaxCode {
        Text taxCode PK
        Text taxDescription
    }

    DocumentType {
        Text docTypeCode PK
        Text documentTypeDescription
    }

    GlAccount ||--|| DocumentType : documentType
    DocumentType ||--o{ ChartOfAccounts : chartOfAccounts

    ActivityType {
        Text activityTypeCode PK
        Text activityDescription
    }

    Skf {
        Text skfCode PK
        Text costCenter FK
        Text skfDescription
    }

    PlanningGroup {
        Text groupCode PK
        Text groupDescription
    }

    PlanningLevel {
        Text levelCode PK
        Text levelDescription
    }

    WorkCenter {
        Text workCenterCode PK
        Text plantCode FK       
        Text workCenterName
    }

    _Department{
        Text departmentCode PK
        Text departmentName
    }

    _Employee{
        Text departmentCode PK
        Text departmentName
    }

    %% PR && PO
    PR {
        Text prCode PK
        Text requestedBy FK
        Text approvedBy FK
        Text requestedDepartment FK
    }
    PRDetails {
        Text maVatTu FK
        Text maPR FK
        Number soLuong
        Text wbsElement FK

    }
    PO {
        Text poNumber PK
        Text supplierName
        Text requestedBy FK
        Text approvedBy FK
    }
    PODetails {
        maPO Text PK
        maPR Text FK
        maNCC Text FK
        maNganSach Text FK
        soLuong Number
        donGia Number
    }

    PR }|--|| _Employee: requestedEmployee
    PR }|--|| _Employee: approvedEmployee
    PO }|--|| _Employee: requestedEmployee
    PO }|--|| _Employee: approvedEmployee
    PR }|--|| _Department: requestedDepartment
    PR ||--o{ PRDetails : "details"
    PRDetails }o--|| Material : "Material"
    PRDetails ||--|| WbsElement : "wbsElement"
    PO ||--o{ PODetails : "detail"
    PODetails }o--|| Supplier : "supplier"
    PODetails }o--|| Budget : "budget"
    PODetails }o--|| PR : "pr"
    PODetails ||--|| WbsElement : "wbsElement"

    %% KHO %%
    StorageLocation {
        Text storageLocationCode PK
        Text plantCode FK       
        Text storageLocationName
    }


    OutboundOrder {
        Text outboundOrderCode PK
        Text warehouseName
    }

    OutboundDelivery {
        Text outboundDeliveryCode PK
        Text issuedBy
    }

    InboundOrder {
        Text inboundOrderCode PK
        Text warehouseName
    }

    InboundDelivery {
        Text inboundDeliveryCode PK
        Text receivedBy
    }

    OutboundOrderDetails {
        maLXK Text PK
        maVatTu Text FK
        soLuong Number
    }

    InboundDeliveryDetails {
        maPNK Text PK
        maVatTu Text FK
        soLuong Number
    }

    InboundOrderDetails {
        maLNK Text PK
        maVatTu Text FK
        soLuong Number
    }

    OutboundDeliveryDetails {
        maPXK Text PK
        maVatTu Text FK
        soLuong Number
    }

    StorageLocation ||--o{ Inventory : "stock"
    StorageLocation ||--o{ InboundOrder : "inboundOrder"
    StorageLocation ||--o{ OutboundOrder : "outboundOrder"
    Inventory o{--|| Material : "material"
    InboundOrder o{--|| PO : "po"
    InboundOrder ||--o{ InboundDelivery : "receipt"
    OutboundOrder ||--o{ OutboundDelivery : "delivery"
    InboundOrder ||--|{ InboundOrderDetails : "details"
    InboundDelivery ||--|{ InboundDeliveryDetails : "details"
    OutboundOrder ||--|{ OutboundOrderDetails : "details"
    OutboundDelivery ||--|{ OutboundDeliveryDetails : "details"
    InboundOrderDetails o{--|| Material : "material"
    InboundDeliveryDetails o{--|| Material : "material"
    OutboundOrderDetails o{--|| Material : "material"
    OutboundDeliveryDetails o{--|| Material : "material"
    %% KHO %%
